# R Programming — NPTEL Week 7


`:` creates unit-step sequences. `seq()` gives more control.

In [ ]:
help("seq")

### Increasing sequence

In [ ]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

### Decreasing sequence

In [ ]:
10:1

 [1] 10  9  8  7  6  5  4  3  2  1

### Sequence from 5 to 15

In [ ]:
5:15

 [1]  5  6  7  8  9 10 11 12 13 14 15

### Sequence from 15 to 5

In [ ]:
15:5

 [1] 15 14 13 12 11 10  9  8  7  6  5

### Negative sequence

In [ ]:
-1:-10

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

### Negative sequence

In [ ]:
-10:-1

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

### Negative sequence

In [ ]:
-5:-15

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

### Negative sequence

In [ ]:
-15:-5

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

### Decimal sequence

In [ ]:
1.23:10

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

### Decimal sequence

In [ ]:
1.23:10.54

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

### Decimal sequence

In [ ]:
10.54:2.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

### Decimal sequence

In [ ]:
-1.23:-10

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

### Decimal sequence

In [ ]:
-5.23:6

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

### `seq(10)`

In [ ]:
seq(10)

 [1]  1  2  3  4  5  6  7  8  9 10

### Equivalent form

In [ ]:
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

### Sequence with a predefined variable
`seq(from, to, by)` controls the start, end and increment.

In [ ]:
x=2

In [ ]:
seq(1, x, x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

In [ ]:
x=50

In [ ]:
seq(0, x, x/10)

 [1]  0  5 10 15 20 25 30 35 40 45 50

### Store and transform a sequence
The result can be stored and arithmetic is applied element-by-element.

In [ ]:
x = seq(1, 50, 1/2)

In [ ]:
x

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

In [ ]:
y=2*x

In [ ]:
y

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

### Index vector
`seq(along=x)` creates the positions of the elements.

In [ ]:
x = c(9,8,7,6)

In [ ]:
ind = seq(along=x)

In [ ]:
ind

[1] 1 2 3 4

In [ ]:
x[ ind[2] ]

[1] 8

### Current date and time

In [ ]:
Sys.time()

[1] "2026-09-01 09:12:59 UTC"

### Current date

In [ ]:
Sys.Date()

[1] "2026-09-01"

## Lecture 27 — Sequences of Dates and Alphabets

`as.Date()` creates Date objects. `by` controls the date interval.

### First day of each year

In [ ]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by = "years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

### Six yearly dates

In [ ]:
seq(as.Date("2017-01-01"), by = "years", length = 6)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

### Six daily dates

In [ ]:
seq(as.Date("2017-01-01"), by = "days", length = 6)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

### Six monthly dates

In [ ]:
seq(as.Date("2017-01-01"), by = "months", length = 6)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

### Date sequence using start and end dates

In [ ]:
startdate = as.Date("2016-1-1")

In [ ]:
enddate = as.Date("2017-1-1")

In [ ]:
out = seq(enddate, startdate, by = "-1 month")

In [ ]:
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

### Lowercase alphabets
`letters` contains the lowercase alphabet.

In [ ]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [ ]:
letters[1:3]

[1] "a" "b" "c"

In [ ]:
letters[3:1]

[1] "c" "b" "a"

In [ ]:
letters[21:23]

[1] "u" "v" "w"

In [ ]:
letters[2]

[1] "b"

### Uppercase alphabets
`LETTERS` contains the uppercase alphabet.

In [ ]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [ ]:
LETTERS[1:3]

[1] "A" "B" "C"

In [ ]:
LETTERS[3:1]

[1] "C" "B" "A"

In [ ]:
LETTERS[21:23]

[1] "U" "V" "W"

In [ ]:
LETTERS[2]

[1] "B"

## Lecture 28 — Repeats

`rep()` repeats values. `times` repeats the whole object; `each` repeats each element.

### `rep()` help

In [ ]:
help("rep")

### Repeat a value 10 times

In [ ]:
rep(3.5, times=10)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

### Repeat a vector twice

In [ ]:
rep(1:4, 2)

[1] 1 2 3 4 1 2 3 4

### `times` versus `each`

In [ ]:
x = 1:4

In [ ]:
x

[1] 1 2 3 4

In [ ]:
rep(x, times = 3)

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

In [ ]:
rep(x, each = 3)

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

### Combine `each` and `times`

In [ ]:
rep(1:4, each = 2)

[1] 1 1 2 2 3 3 4 4

In [ ]:
rep(1:4, each = 2, times = 3)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

In [ ]:
rep(1:4, times = 3, each = 2)

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

### Different repetition counts

In [ ]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [ ]:
ans = seq(from=2, to=8, by=2)

In [ ]:
ans

[1] 2 4 6 8

In [ ]:
rep(1:4, ans)

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

### Repeat a matrix
R stores matrix values column-wise.

In [ ]:
x = matrix(nrow=2, ncol=2, data=1:4, byrow=T)

In [ ]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [ ]:
rep(x, 3)

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

### Repeat character values

In [ ]:
rep(c("a", "b", "c"), 2)

[1] "a" "b" "c" "a" "b" "c"

In [ ]:
rep(c("apple", "banana", "cake"), 2)

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

### Repeat to a specified length

In [ ]:
rep(2, length.out=5)

[1] 2 2 2 2 2

In [ ]:
rep(2, length=5)

[1] 2 2 2 2 2

In [ ]:
rep(c(2,3), length=5)

[1] 2 3 2 3 2

In [ ]:
rep(c(2,3,4), length=5)

[1] 2 3 4 2 3

In [ ]:
rep("apple", length=5)

[1] "apple" "apple" "apple" "apple" "apple"

## Lecture 29 — Sorting, Ordering and Mode

`sort()` returns sorted values. `order()` returns the positions that produce the sorted order.

In [ ]:
y = c(8,5,7,6)

In [ ]:
y

[1] 8 5 7 6

In [ ]:
sort(y)

[1] 5 6 7 8

In [ ]:
sort(y, decreasing = TRUE)

[1] 8 7 6 5

### Sorting with missing values
`na.last=TRUE` puts `NA` last, `FALSE` puts it first, and `NA` removes missing values.

In [ ]:
sort(c(8, NA, 5, 7), na.last=TRUE)

[1]  5  7  8 NA

In [ ]:
sort(c(8, NA, 5, 7), na.last=FALSE)

[1] NA  5  7  8

In [ ]:
sort(c(8, NA, 5, 7), na.last=NA)

[1] 5 7 8

### `order()`

In [ ]:
y = c(9,8,5,7,6)

In [ ]:
y

[1] 9 8 5 7 6

In [ ]:
order(y)

[1] 3 5 4 2 1

In [ ]:
order(y, decreasing = TRUE)

[1] 1 2 4 5 3

### `mode()`
Shows the storage mode of an R object.

In [ ]:
mode(2.432)

[1] "numeric"

In [ ]:
mode(c(3,4,5,6,7,8))

[1] "numeric"

In [ ]:
mode("India")

[1] "character"

In [ ]:
mode(c("India", "CANADA"))

[1] "character"

In [ ]:
mode(factor(c("UP", "MP")))

[1] "numeric"

In [ ]:
mode(list("India", "USA"))

[1] "list"

In [ ]:
mode(data.frame(x=1:2, y=c("India", "USA")))

[1] "list"

In [ ]:
mode(print)

[1] "function"

## Lecture 30 — Lists

A list can contain objects of different types, including vectors, matrices, data frames and other lists.

### Matrices used in the examples

In [ ]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)

In [ ]:
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)

In [ ]:
x1

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [ ]:
x2

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [ ]:
x1+x2

     [,1] [,2]
[1,]  6    8
[2,] 10   12

### Put character data into a numeric matrix
A matrix has one common data type, so the numeric values become character.

In [ ]:
x1[2,1] = "hello"

In [ ]:
x1

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

In [ ]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)

In [ ]:
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)

### Create a list containing the two matrices

In [ ]:
matlist = list(x1, x2)

In [ ]:
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

### Access list elements with `[ ]`
Single brackets return a sublist.

In [ ]:
matlist[1]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

In [ ]:
matlist[2]

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

### List containing different object types
The elements are a character vector, a numeric vector and a matrix.

In [ ]:
z1 = list( c("water", "juice", "lemonade"), rep(1:4, each=2), matrix(data=5:8, nrow=2, ncol=2, byrow=T) )

In [ ]:
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

### Access an element with `[[ ]]`
Double brackets extract the actual list element.

In [ ]:
z1[[1]]

[1] "water"    "juice"    "lemonade"

### `[ ]` versus `[[ ]]`
The first form operates on a sublist. The second extracts the vector first and then selects its second value.

In [ ]:
z1[1][2]

[[1]]
NULL

In [ ]:
z1[[1]][2]

[1] "juice"

### Named list elements
Named elements can be accessed with either `[[ ]]` or `$`.

In [ ]:
students = list(Students=c("A", "B"), Marks=c(90, 85))

In [ ]:
students[["Students"]]

[1] "A" "B"

In [ ]:
students$Students

[1] "A" "B"

# Summary

- `:` → unit-step sequence
- `seq()` → flexible sequence generation
- `Sys.time()` → current date and time
- `Sys.Date()` → current date
- `letters` → lowercase alphabet
- `LETTERS` → uppercase alphabet
- `rep()` → repetition
- `times` → repeat the whole object
- `each` → repeat each element
- `sort()` → sorted values
- `order()` → sorting positions
- `mode()` → storage mode
- `list()` → stores different object types together
- `[ ]` → subset or sublist
- `[[ ]]` → actual list element