The  print function has a significant limitation that it prints only one
object at a  time.

In [ ]:
print("The zero occurs at", 2*pi, "radians.")

ERROR: Error in print.default("The zero occurs at", 2 * pi, "radians."): invalid 'quote' argument

Only way to print multiple items is to print them one at a time

In [ ]:
print("The zero occurs at"); print(2*pi); print("radians");

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

"cat" function

In [ ]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

In [ ]:
d = date()
cat("Today's date is: ", d, "\n")

Today's date is:  Tue Sep 22 09:02:07 2026

In [ ]:
x = 1:10
x
cat(x, sep=" ++ ")
cat("\n")
cat(x, sep=" / ")

 [1]  1  2  3  4  5  6  7  8  9 10

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [ ]:
x = 7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [ ]:
cat("The square root of",x,"is approximately", format(sqrt(x),digits=3),"\n")

The square root of 7 is approximately 2.65

The cat function can also print simple vectors

In [ ]:
evenno = c(2,4,6,8,10)
evenno
cat("The first few even numbers are:", evenno, "...\n")

[1]  2  4  6  8 10

The first few even numbers are: 2 4 6 8 10 ...

In [ ]:
x = 1:10
x
cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

 [1]  1  2  3  4  5  6  7  8  9 10

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

The  paste() function concatenates several strings together.

In [ ]:
paste(1:12)
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [ ]:
 paste("Everybody", "loves", "R Programming.")
 paste("Everybody", "loves", "R Programming.", sep="*")
 paste("Everybody", "loves", "R Programming.", sep="===")

[1] "Everybody loves R Programming."

[1] "Everybody*loves*R Programming."

[1] "Everybody===loves===R Programming."

If one or more arguments are vectors of strings, paste will generate
all combinations of the arguments:

In [ ]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
names
paste(names, "is", "a good", "person.")

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

In [ ]:
paste(1, " is first", 2, " is second", 3, " is third", sep = "#")

[1] "1# is first#2# is second#3# is third"

In [ ]:
paste(1, " is first ", 2, " is second ", 3, " is third ", sep = "#")

[1] "1# is first #2# is second #3# is third "

In [ ]:
 x = paste("Ex", 1:5, sep="_")
 x
 x[1]
 x[5]

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1"

[1] "Ex_5"

In [ ]:
x = paste("Ex", 1:5, sep="_", collapse="")
x[1]

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

paste VS paste0

In [ ]:
paste0(1:10)
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [ ]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

Command strsplit:  split the elements of a character vector.

In [ ]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x
strsplit(x, split='!')
strsplit(x, split='&!')

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

In [ ]:
 x = "The&!syntax&!of&!paste&!is!&available!&inthe online-help"
 x
 y = strsplit(x, split = "!&")
 y

[1] "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

[[1]]
[1] "The&!syntax&!of&!paste&!is" "available"
[3] "inthe online-help"

In [ ]:
y[[1]][1]
y[[1]][3]

[1] "The&!syntax&!of&!paste&!is"

[1] "inthe online-help"

Convert to Matrix

In [ ]:
dates = c("2020-07-24", "2021-08-25", "2022-09-26", "2023-10-27")
datesplt = strsplit(dates, "-")
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

In [ ]:
datemat = matrix(unlist(datesplt), nrow = 4, ncol=3, byrow=TRUE)
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

In [ ]:
datematrix = matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol=3, byrow=TRUE)
datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [ ]:
strsplit("Shalabh",split="")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

Operations with Strings: Counting characters

In [ ]:
x = "R course 24.07.2022"
y = "Number of participants: 25"
nchar(x)
nchar(y)

[1] 19

[1] 26

In [ ]:
x = c("Apple", "Banana", "Cake")
nzchar(x)
nchar(x)
y = c("Apple", "", "Cake")
nzchar(y)

[1] TRUE TRUE TRUE

[1] 5 6 4

[1]  TRUE FALSE  TRUE

In [ ]:
y = c(2,4,6)
nchar(y)
z=c(11, 222, 3333)
nchar(z)
z1 = c(1.1, 2.22, 3.333)
nchar(z1)

[1] 1 1 1

[1] 2 3 4

[1] 3 4 5

Operations with Strings: Lower and upper cases

In [ ]:
x = "R course will start from 24.07.2022"
toupper(x)

z = "INDIAN INSTITUTE OF TECHNOLOGY"
tolower(z)

[1] "R COURSE WILL START FROM 24.07.2022"

[1] "indian institute of technology"