# R Programming NPTEL — Week 5

## Missing Data: Detecting NA

In [1]:
x = NA
is.na(x)

[1] TRUE

In [2]:
x = c(11, NA, 13, NA)
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

## Missing Data: Calculations

In [3]:
x = c(11, NA, 13, NA)
mean(x)

[1] NA

In [4]:
mean(x, na.rm = TRUE)

[1] 12

## NA and NULL

In [5]:
x = NA
x

[1] NA

In [6]:
y = NULL
y

NULL

## Missing Data: Locating and Counting

In [7]:
x = c(11, NA, 13, NA)
x
which(is.na(x))

[1] 11 NA 13 NA

[1] 2 4

In [8]:
x = c(11, NA, 13, NA)
x
sum(is.na(x))

[1] 11 NA 13 NA

[1] 2

## Missing Data: Complete Cases and Omission

In [9]:
x = c(11, NA, 13, NA)
x
complete.cases(x)

[1] 11 NA 13 NA

[1]  TRUE FALSE  TRUE FALSE

In [10]:
x = c(11, NA, 13, NA)
y = na.omit(x)
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [11]:
x = c(11, NA, 13, NA)
y = na.omit(x)
y
mean(x)
mean(y)

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

[1] NA

[1] 12

## Conditional Execution: if

In [12]:
x = 5
if (x > 4) x * 3

[1] 15

In [13]:
x = 3
if (x > 4) x * 3

In [14]:
x = 5
if (x > 4) {x * 3}

[1] 15

In [15]:
x = 3
if (x > 4) {x * 3}

Example: print when the value is more than 3.

In [16]:
x = 6
if (x > 3) {
  print("The value is more than 3")
}

[1] "The value is more than 3"

Example where the condition is false.

In [17]:
x = 2
if (x > 3) {
  print("The value is more than 3")
}

## Conditional Execution: if-else

In [18]:
x = 5
if (x == 3) { x = x - 1 } else { x = 2*x }
x

[1] 10

In [19]:
x = 3
if (x == 3) { x = x - 1 } else { x = 2*x }
x

[1] 2

Example with x = 6.

In [20]:
x = 6
if (x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is more than 3"

Example with x = 2.

In [21]:
x = 2
if (x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is less than 3"

## Nested if-else if

In [22]:
x = 5
if (x == 3) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else {
  x = 2*x
}
x

[1] 10

In [23]:
x = 2
if (x == 3) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else {
  x = 2*x
}
x

[1] 7

In [24]:
x = 3
if (x == 3) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else {
  x = 2*x
}
x

[1] 2

## Conditional Execution: ifelse

In [25]:
x = 1:10
x
ifelse(x < 6, x^2, x + 1)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  4  9 16 25  7  8  9 10 11

In [26]:
x = c(7, 9, 8, 4)
ifelse(x %% 2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

## Conditional Execution: switch

In [27]:
switch(2, "apple", "banana", "orange")

[1] "banana"

In [28]:
switch(1, "apple", "banana", "orange")

[1] "apple"

In [29]:
switch("colour", "colour" = "blue", "gender" = "male", "volume" = 50)

[1] "blue"

In [30]:
switch("volume", "colour" = "blue", "gender" = "male", "volume" = 50)

[1] 50

In [31]:
switch(4, "apple", "banana", "orange")

In [32]:
switch("size", "colour" = "blue", "gender" = "male", "volume" = 50)

## Conditional Execution: which

In [33]:
x = c(10, 15, 8, 14, 6, 12)
x
which(x == 14)

[1] 10 15  8 14  6 12

[1] 4

In [34]:
x = c(10, 15, 8, 14, 6, 12)
which(x != 12)

[1] 1 2 3 4 5

In [35]:
x = c(10, 15, 8, 14, 6, 12)
which(x > 10)

[1] 2 4 6

In [36]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)
x
which.min(x)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1

In [37]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)
which.max(x)

[1] 9

In [38]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)
x
which(x %% 2 == 1)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1 3 5 7 9

In [39]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)
which(x %% 2 == 1, arr.ind = TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3