# R Programming NPTEL — Week 11

## Data Frames and Summary

In [15]:
library(MASS)
painters

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A
F. Zucarro      10          13       8      8         B
Fr. Salviata    13          15       8      8         B
Parmigiano      10          15       6      6         B
Primaticcio     15          14       7     10         B
T. Zucarro      13          14      10      9         B
Volterra        12          15       5      8         B
Barocci         14          15       6     10         C
Cortona         16          14      12      6         C
Josepin         10          10       6      2         C
L. Jordaens     13          12       9      6         C
Testa           11          15       0      6         C
Vanius          15          15      12     13         C
Bassano          6           8      17      0         D
Bellini          4           6      14      0         D
Giorgione        8           9      18      4         D
Murillo          6           8      15      4         D
Palma Giovane   12           9      14      6         D
Palma Vecchio    5           6      16      0         D
Pordenone        8          14      17      5         D
Tintoretto      15          14      16      4         D
Titian          12          15      18      6         D
Veronese        15          10      16      3         D
Albani          14          14      10      6         E
Caravaggio       6           6      16      0         E
Corregio        13          13      15     12         E
Domenichino     15          17       9     17         E
Guercino        18          10      10      4         E
Lanfranco       14          13      10      5         E
The Carraci     15          17      13     13         E
Durer            8          10      10      8         F
Holbein          9          10      16     13         F
Pourbus          4          15       6      6         F
Van Leyden       8           6       6      4         F
Diepenbeck      11          10      14      6         G
J. Jordaens     10           8      16      6         G
Otho Venius     13          14      10     10         G
Rembrandt       15           6      17     12         G
Rubens          18          13      17     17         G
Teniers         15          12      13      6         G
Van Dyck        15          10      17     13         G
Bourdon         10           8       8      4         H
Le Brun         16          16       8     16         H
Le Suer         15          15       4     15         H
Poussin         15          17       6     15         H

In [16]:
summary(painters$School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

In [17]:
attach(painters)

In [18]:
summary(School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

In [19]:
summary(Composition)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

In [20]:
detach(painters)

In [21]:
summary(painters$School)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

## Subsetting and Splitting Data Frames

In [22]:
subset(painters, School == "F")

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

In [23]:
painters[painters[["School"]] == "F", ]

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

In [24]:
subset(painters, Composition <= 6)

              Composition Drawing Colour Expression School
Fr. Penni     0           15       8     0          A
Perugino      4           12      10     4          A
Bassano       6            8      17     0          D
Bellini       4            6      14     0          D
Murillo       6            8      15     4          D
Palma Vecchio 5            6      16     0          D
Caravaggio    6            6      16     0          E
Pourbus       4           15       6     6          F

In [25]:
subset(painters, School == "F", select = c(-3, -5))

           Composition Drawing Expression
Durer      8           10       8
Holbein    9           10      13
Pourbus    4           15       6
Van Leyden 8            6       4

In [26]:
splitted = split(painters, painters$School)
splitted

$A
                Composition Drawing Colour Expression School
Da Udine                 10       8     16          3      A
Da Vinci                 15      16      4         14      A
Del Piombo                8      13     16          7      A
Del Sarto                12      16      9          8      A
Fr. Penni                 0      15      8          0      A
Guilio Romano            15      16      4         14      A
Michelangelo              8      17      4          8      A
Perino del Vaga          15      16      7          6      A
Perugino                  4      12     10          4      A
Raphael                  17      18     12         18      A

$B
             Composition Drawing Colour Expression School
F. Zucarro            10      13      8          8      B
Fr. Salviata          13      15      8          8      B
Parmigiano            10      15      6          6      B
Primaticcio           15      14      7         10      B
T. Zucarro            13      14     10          9      B
Volterra              12      15      5          8      B

$C
            Composition Drawing Colour Expression School
Barocci              14      15      6         10      C
Cortona              16      14     12          6      C
Josepin              10      10      6          2      C
L. Jordaens          13      12      9          6      C
Testa                11      15      0          6      C
Vanius               15      15     12         13      C

$D
              Composition Drawing Colour Expression School
Bassano                 6       8     17          0      D
Bellini                 4       6     14          0      D
Giorgione               8       9     18          4      D
Murillo                 6       8     15          4      D
Palma Giovane          12       9     14          6      D
Palma Vecchio           5       6     16          0      D
Pordenone               8      14     17          5      D
Tintoretto             15      14     16          4      D
Titian                 12      15     18          6      D
Veronese               15      10     16          3      D

$E
            Composition Drawing Colour Expression School
Albani               14      14     10          6      E
Caravaggio            6       6     16          0      E
Corregio             13      13     15         12      E
Domenichino          15      17      9         17      E
Guercino             18      10     10          4      E
Lanfranco            14      13     10          5      E
The Carraci          15      17     13         13      E

$F
           Composition Drawing Colour Expression School
Durer                8      10     10          8      F
Holbein              9      10     16         13      F
Pourbus              4      15      6          6      F
Van Leyden           8       6      6          4      F

$G
            Composition Drawing Colour Expression School
Diepenbeck           11      10     14          6      G
J. Jordaens          10       8     16          6      G
Otho Venius          13      14     10         10      G
Rembrandt            15       6     17         12      G
Rubens               18      13     17         17      G
Teniers              15      12     13          6      G
Van Dyck             15      10     17         13      G

$H
        Composition Drawing Colour Expression School
Bourdon          10       8      8          4      H
Le Brun          16      16      8         16      H
Le Suer          15      15      4         15      H
Poussin          15      17      6         15      H

In [27]:
is.data.frame(splitted$A)

[1] TRUE

## Writing Data Files

In [31]:
x = c(1:100)
x

  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [32]:
write(x, file = "shalabh")

In [33]:
write(x, file = "data", ncolumns = 5, append = FALSE, sep = " ")

In [34]:
sample_data = data.frame(Name = c("A", "B", "C"), Score = c(75, 88, 92))
write.csv(sample_data, file = "sample_data.csv", row.names = FALSE)

In [35]:
write.table(sample_data, file = "sample_data.txt", row.names = FALSE, sep = "\t")