# R Programming NPTEL — Week 4

## Matrix Operations and Logical Operators

## 1. Matrix Row and Column Names

In [102]:
x = matrix(nrow=4, ncol=3, data=c(1:12))

In [103]:
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [104]:
rownames(x) = c("r1", "r2", "r3", "r4")

In [105]:
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [106]:
colnames(x) = c("c1", "c2", "c3")

In [107]:
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

## 2. Assigning a Constant to Matrix Elements

In [108]:
x = matrix(nrow=4, ncol=2, data=2)

In [109]:
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

## 3. Diagonal Matrices

In [110]:
d = diag(1, nrow=3, ncol=3)

In [111]:
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [112]:
d = diag(5, nrow=3, ncol=3)

In [113]:
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

## 4. Transpose of a Matrix

In [114]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [115]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [116]:
xt = t(x)

In [117]:
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

## 5. Row and Column Sums

In [118]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))

In [119]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [120]:
rowSums(x)

[1]  6  8 10 12

In [121]:
colSums(x)

[1] 10 26

## 6. Row and Column Means

In [122]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))

In [123]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [124]:
rowMeans(x)

[1] 3 4 5 6

In [125]:
colMeans(x)

[1] 2.5 6.5

## 7. Accessing Rows, Columns, and Submatrices

In [126]:
x = matrix(nrow=5, ncol=3, byrow=T, data=1:15)

In [127]:
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [128]:
x[3,]

[1] 7 8 9

In [129]:
x[,2]

[1]  2  5  8 11 14

In [130]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [131]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

## 8. Matrix and Scalar Arithmetic

In [132]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [133]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [134]:
x + 5

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

In [135]:
x - 5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

In [136]:
5*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [137]:
x/2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

## 9. Addition and Subtraction of Matrices

In [138]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [139]:
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)

In [140]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [141]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

In [142]:
x + y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

In [143]:
x - y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

In [144]:
4*x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

In [145]:
x + 4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [146]:
4*x - x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

## 10. Matrix Multiplication

In [147]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [148]:
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)

In [149]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [150]:
y

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

In [151]:
x%*%y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [152]:
y%*%x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

## 11. Multiplication with Transpose

In [153]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [154]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [155]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [156]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [157]:
x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

## 12. Cross Product

In [158]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [159]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [160]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [161]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

## 13. Concatenating Matrices

In [162]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)

In [163]:
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)

In [164]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

In [165]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

In [166]:
rbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

In [167]:
cbind(x, y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

## 14. Inverse of a Matrix

In [168]:
y = matrix(nrow=2, ncol=2, byrow=T, data=c(84,100,100,120))

In [169]:
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [170]:
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

## 15. Eigenvalues and Eigenvectors

In [171]:
y = matrix(nrow=2, ncol=2, byrow=T, data=c(84,100,100,120))

In [172]:
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [173]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

## 16. Logical Operators: OR

In [174]:
x=8

In [175]:
(x < 10) || (x < 2)

[1] TRUE

In [176]:
x=18

In [177]:
(x < 10) || (x < 2)

[1] FALSE

In [178]:
x = c(8,18)

In [179]:
(x < 10) | (x < 2)

[1]  TRUE FALSE

## 17. Logical Operators: AND

In [180]:
x = 5

In [181]:
(x < 10) && (x > 2)

[1] TRUE

In [182]:
x = 15

In [183]:
(x < 10) && (x > 2)

[1] FALSE

In [184]:
x = c(8,18)

In [185]:
(x < 10) & (x > 2)

[1]  TRUE FALSE

## 18. Filtering with Logical Conditions

In [186]:
x = 1:6

In [187]:
(x > 2) & (x < 5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [188]:
x[(x > 2) & (x < 5)]

[1] 3 4

In [189]:
(x > 2) | (x < 5)

[1] TRUE TRUE TRUE TRUE TRUE TRUE

In [190]:
x[(x > 2) | (x < 5)]

[1] 1 2 3 4 5 6

In [191]:
(x[1] > 2) & (x[1] < 5)

[1] FALSE

## 19. Standard Logical Operations

In [192]:
x = TRUE

In [193]:
y = FALSE

In [194]:
x & y

[1] FALSE

In [195]:
x | y

[1] TRUE

In [196]:
!x

[1] FALSE

In [197]:
xor(x,y)

[1] TRUE

In [198]:
isTRUE(x)

[1] TRUE

In [199]:
isFALSE(y)

[1] TRUE

## 20. Testing Logical Values

In [200]:
x = 5

In [201]:
Logical1 = (x > 2)

In [202]:
Logical1

[1] TRUE

In [203]:
is.logical(Logical1)

[1] TRUE

In [204]:
Logical2 = (x < 10)

In [205]:
Logical2

[1] TRUE

In [206]:
is.logical(Logical2)

[1] TRUE

In [207]:
Logical3 = (x != 5)

In [208]:
Logical3

[1] FALSE

In [209]:
is.logical(Logical3)

[1] TRUE

In [210]:
Logical4 = (2*x > 11)

In [211]:
Logical4

[1] FALSE

In [212]:
is.logical(Logical4)

[1] TRUE

In [213]:
Logical5 = (3*x <20)

In [214]:
Logical5

[1] TRUE

In [215]:
is.logical(Logical5)

[1] TRUE

## 21. Relational Operators

In [216]:
8 > 7

[1] TRUE

In [217]:
7 < 5

[1] FALSE

In [218]:
7 > 7

[1] FALSE

In [219]:
7 >= 7

[1] TRUE

In [220]:
8 < 8

[1] FALSE

In [221]:
8 <= 8

[1] TRUE

In [222]:
8 != 9

[1] TRUE

In [223]:
9 != 9

[1] FALSE

In [224]:
7 == 7

[1] TRUE

In [225]:
7 == 8

[1] FALSE

In [226]:
x = TRUE

In [227]:
!x

[1] FALSE

## 22. Comparing Vectors

In [228]:
x = c(1, 2, 3)

In [229]:
y = c(4, 5, 6)

In [230]:
x > y

[1] FALSE FALSE FALSE

In [231]:
x < y

[1] TRUE TRUE TRUE

In [232]:
x != y

[1] TRUE TRUE TRUE

In [233]:
x == y

[1] FALSE FALSE FALSE

## 23. isTRUE() and isFALSE() Examples

In [234]:
isTRUE(8 < 6)

[1] FALSE

In [235]:
isTRUE(8 > 6)

[1] TRUE

In [236]:
isFALSE(5 < 8)

[1] FALSE

In [237]:
isFALSE(5 > 8)

[1] TRUE