# R Programming — Week 3

## Power Operations, Built-in Functions, Assignments, and Matrices

## 1. Power Operations

In [1]:
2^3

[1] 8

In [2]:
2**3

[1] 8

In [3]:
2^0.5

[1] 1.414214

In [4]:
2**0.5

[1] 1.414214

In [5]:
2^-0.5

[1] 0.7071068

In [6]:
c(2, 3, 5, 7)^2

[1]  4  9 25 49

In [7]:
c(2, 3, 5, 7)^c(2, 3)

[1]   4  27  25 343

In [8]:
c(1, 2, 3, 4, 5, 6)^c(2, 3, 4)

[1]    1    8   81   16  125 1296

In [9]:
c(2, 3, 5, 7)^c(2, 3, 4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

## 2. Integer Division

In [10]:
2 %/% 2

[1] 1

In [11]:
5 %/% 2

[1] 2

In [12]:
7 %/% 3

[1] 2

In [13]:
c(2, 3, 5, 7) %/% 2

[1] 1 1 2 3

In [14]:
c(2, 3, 5, 7) %/% c(2, 3)

[1] 1 1 2 2

In [15]:
c(2, 3, 5) %/% c(2, 3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

## 3. Modulo Division

In [16]:
2 %% 2

[1] 0

In [17]:
3 %% 2

[1] 1

In [18]:
7 %% 3

[1] 1

In [19]:
7 %% 4

[1] 3

In [20]:
c(2, 3, 5, 7) %% 2

[1] 0 1 1 1

In [21]:
c(2, 3, 5, 7) %% c(2, 3)

[1] 0 0 1 1

In [22]:
c(2, 3, 5) %% c(2, 3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

## 4. Maximum and Minimum

In [23]:
max(1.2, 3.4, -7.8)

[1] 3.4

In [24]:
max(c(1.2, 3.4, -7.8))

[1] 3.4

In [25]:
min(1.2, 3.4, -7.8)

[1] -7.8

In [26]:
min(c(1.2, 3.4, -7.8))

[1] -7.8

## 5. Mean and Other Built-in Functions

In [27]:
mean(2, 3, 4)

[1] 2

In [28]:
mean(c(2, 3, 4))

[1] 3

In [29]:
abs(-4)

[1] 4

In [30]:
abs(c(-1, -2, -3, 4, 5))

[1] 1 2 3 4 5

In [31]:
sqrt(4)

[1] 2

In [32]:
sqrt(c(4, 9, 16, 25))

[1] 2 3 4 5

In [33]:
sum(c(2, 3, 5, 7))

[1] 17

In [34]:
prod(c(2, 3, 5, 7))

[1] 210

In [35]:
round(1.23)

[1] 1

In [36]:
round(1.83)

[1] 2

In [37]:
log(10)

[1] 2.302585

In [38]:
log(exp(1))

[1] 1

In [39]:
log(c(10, 100, 1000))

[1] 2.302585 4.605170 6.907755

In [40]:
log10(10)

[1] 1

In [41]:
log10(100)

[1] 2

In [42]:
log10(c(10, 100, 1000))

[1] 1 2 3

## 6. Assignments and Combined Calculations

In [43]:
x1 = c(1, 2, 3, 4)

In [44]:
x1

[1] 1 2 3 4

In [45]:
x2 = x1^2

In [46]:
x2

[1]  1  4  9 16

In [47]:
c(1, 2, 3, 4) + sum(c(1, 2, 3, 4)) * prod(c(1, 2))

[1] 21 22 23 24

In [48]:
abs(c(1, 2, 3, 4) - sum(c(1, 2, 3, 4)) * prod(c(1, 2)))

[1] 19 18 17 16

## 7. Creating Matrices

In [49]:
x = matrix(nrow = 4, ncol = 2, data = c(1, 2, 3, 4, 5, 6, 7, 8))

In [50]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [51]:
x = matrix(nrow = 4, ncol = 2, data = c(1, 2, 3, 4, 5, 6, 7, 8), byrow = FALSE)

In [52]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [53]:
y = matrix(nrow = 4, ncol = 2, data = c(1, 2, 3, 4, 5, 6, 7, 8), byrow = TRUE)

In [54]:
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

## 8. Accessing Matrix Elements

In [55]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [56]:
x[3, 2]

[1] 7

## 9. Matrix Properties

In [57]:
dim(x)

[1] 4 2

In [58]:
nrow(x)

[1] 4

In [59]:
ncol(x)

[1] 2

In [60]:
mode(x)

[1] "numeric"

In [61]:
attributes(x)

$dim
[1] 4 2

## 10. Matrix Help and Examples

In [62]:
help("matrix")

In [63]:
is.matrix(as.matrix(1:10))

[1] TRUE

In [64]:
data(warpbreaks)

In [65]:
!is.matrix(warpbreaks)

[1] TRUE

In [66]:
warpbreaks[1:10, ]

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M

In [67]:
as.matrix(warpbreaks[1:10, ])

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M